import = [
  # uncomment the flavour you want below:
 # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  #"~/.config/alacritty/catppuccin-mocha.toml"
]
# Fonte
[font]
size = 11.0

[font.normal]
family = "Fira Code Nerd Font"
style = "Regular"

# Opacidade da janela
[window]
opacity = 0.8

# Padding (espaçamento interno da janela)
[window.padding]
x = 10
y = 14
[colors.primary]
background = "#15141b"
foreground = "#edecee"

[colors.cursor]
cursor = "#a277ff"

[colors.selection]
text = "CellForeground"
background = "#29263c"

[colors.normal]
black = "#110f18"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

[colors.bright]
black = "#4d4d4d"
red = "#ff6767"
green = "#61ffca"
yellow = "#ffca85"
blue = "#a277ff"
magenta = "#a277ff"
cyan = "#61ffca"
white = "#edecee"

#[shell]
#program = "/usr/bin/zsh"
#args = ["-c", "fortune -s | cowsay -f tux | lolcat; exec zsh"]
